#!/usr/bin/env bash
set -euo pipefail

# Setup auth
if [ $(kubectl config get-clusters | wc -l) -eq 1 ]; then
    echo "$KUBE64" | base64 -d > kube-config.yaml
    export KUBECONFIG=kube-config.yaml
fi

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="${OUTPUT_FILE:-$REPO_ROOT/scripts/config.yaml}"
CHECK_INTERVAL="${CHECK_INTERVAL:-5m}"
CERTIFICATE_EXPIRATION_THRESHOLD="${CERTIFICATE_EXPIRATION_THRESHOLD:-48h}"

# Kubernetes contexts to scan
CONTEXTS=(
cedille-k8s-cedille-sandbox-gatus
cedille-k8s-shared-gatus
)

# Temporary file to store all discovered endpoints
TEMP_ENDPOINTS=$(mktemp)
trap 'rm -f "$TEMP_ENDPOINTS"' EXIT

echo "Discovering endpoints across clusters..."

# Discover endpoints from all clusters
for ctx in "${CONTEXTS[@]}"; do
  # Check if context exists
  if ! kubectl config get-contexts "$ctx" &>/dev/null; then
    echo "Warning: Context $ctx not found, skipping..."
    continue
  fi

  # Get HTTPProxy endpoints and prefer gatus annotations when present
  kubectl --context="$ctx" get httpproxies.projectcontour.io -A -o json 2>/dev/null \
    | jq -r '.items[]
    | select(.spec.ingressClassName == null or .spec.ingressClassName == "contour")
    | select(.spec.virtualhost.fqdn != null and .spec.virtualhost.fqdn != "")
    | select((.spec.virtualhost.fqdn | contains("*")) | not)
    | select((.metadata.annotations["gatus.cedille/skip-monitor"] // "false") != "true")
    | . as $item
    | ($item.spec.virtualhost.fqdn) as $fqdn
    | ($item.metadata.annotations["gatus.cedille/health-path"] // ($item.spec.routes[0].conditions[0].prefix // "/")) as $path
    | select(($path | tostring | contains("acme-challenge")) | not)
    | ($item.metadata.annotations["gatus.cedille/protocol"] // "https") as $proto
    | ($item.metadata.annotations["gatus.cedille/skip-monitor"] // "false") as $skip
    | $fqdn + "|" + ($path|tostring) + "|" + $proto + "|" + ($skip|tostring)' >> "$TEMP_ENDPOINTS" || true

  # Get Ingress endpoints and prefer gatus annotations when present
  kubectl --context="$ctx" get ingress -A -o json 2>/dev/null \
    | jq -r '.items[]
    | select(.spec.ingressClassName == null or .spec.ingressClassName == "contour")
    | select((.metadata.name | test("^cm-acme-http-solver")) | not)
    | select((.metadata.labels["acme.cert-manager.io/http01-solver"] // "") != "true")
    | select((.metadata.annotations["gatus.cedille/skip-monitor"] // "false") != "true")
    | . as $item
    | ($item.spec.rules[]? | .host) as $host
    | select($host != null and $host != "" and ($host | contains("*") | not))
    | ($item.metadata.annotations["gatus.cedille/health-path"] // ($item.spec.rules[0].http.paths[0].path // "/")) as $path
    | select(($path | tostring | contains("acme-challenge")) | not)
    | ($item.metadata.annotations["gatus.cedille/protocol"] // "https") as $proto
    | ($item.metadata.annotations["gatus.cedille/skip-monitor"] // "false") as $skip
    | ($host // "") + "|" + ($path|tostring) + "|" + $proto + "|" + ($skip|tostring)' >> "$TEMP_ENDPOINTS" || true
done

# Sort discovered endpoints (prioritizing specific paths over root '/')
UNIQUE_ENDPOINTS=$(sort -t'|' -k1,1 -k2,2r -u "$TEMP_ENDPOINTS")

# Generate Gatus config.yaml
cat > "$OUTPUT_FILE" <<'EOF'
# Auto-generated Gatus configuration
# Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Do not edit manually - this file is automatically generated
metrics: true
skip-invalid-config-update: true

storage:
  type: sqlite
  path: /data/gatus.db

alerting:
  discord:
    enabled: true
    webhook-url: "https://discord.com/api/webhooks/1523550041023709316/BegnppsG4eohO5Huai-SC2krnOW1hWBNf68IH73FAUvLzOdRT9OeT0et47_oCr-KO9Rh"

# Web UI configuration
web:
  port: 8080

# Endpoints to monitor
endpoints:
EOF

# Dictionary / associative arrays to track already added endpoints for O(1) deduplication
declare -A SEEN_NAMES
declare -A SEEN_HOSTS
CONFIGURED_COUNT=0

# Add each endpoint to the config
while IFS= read -r endpoint; do
  # Skip empty lines
  [[ -z "$endpoint" ]] && continue

  # Each discovered line is stored as: host|path|protocol|skip
  HOST=$(echo "$endpoint" | cut -d '|' -f1 | tr -d '[:space:]')
  PATH_VAL=$(echo "$endpoint" | cut -d '|' -f2 | tr -d '[:space:]')
  PROTO=$(echo "$endpoint" | cut -d '|' -f3 | tr -d '[:space:]')
  SKIP=$(echo "$endpoint" | cut -d '|' -f4 | tr -d '[:space:]')

  # Respect explicit skip annotation
  if [[ "$SKIP" == "true" ]]; then
    continue
  fi

  # Skip obvious invalid, local-only or wildcard hosts
  if [[ -z "$HOST" ]] || [[ "$HOST" == *"*"* ]] || [[ "$HOST" == *".local"* ]] || [[ "$HOST" == *"minikube"* ]] || [[ "$HOST" == *"localhost"* ]]; then
    continue
  fi

  # Skip ACME challenge paths
  if [[ "$PATH_VAL" == *"acme-challenge"* ]] || [[ "$PATH_VAL" == *".well-known"* ]]; then
    continue
  fi

  # Sanitize endpoint name (lowercase, alphanumeric and hyphens only)
  ENDPOINT_NAME=$(echo "$HOST" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9-]+/-/g' | sed -E 's/^-+|-+$//g')

  if [[ -z "$ENDPOINT_NAME" ]]; then
    continue
  fi

  # Deduplication check: skip if endpoint name or host has already been added
  if [[ -n "${SEEN_NAMES[$ENDPOINT_NAME]:-}" ]] || [[ -n "${SEEN_HOSTS[$HOST]:-}" ]]; then
    echo "Ignored duplicate endpoint: $ENDPOINT_NAME ($HOST)"
    continue
  fi

  # Register in dictionary
  SEEN_NAMES["$ENDPOINT_NAME"]=1
  SEEN_HOSTS["$HOST"]=1

  # Determine group based on domain patterns
  GROUP="production"
  if [[ "$HOST" == *"etsmtl.club"* ]]; then
      GROUP="shared"
  elif [[ "$HOST" == *"staging"* ]] || [[ "$HOST" == *"dev"* ]]; then
      GROUP="staging"
  elif [[ "$HOST" == *"internal"* ]] || [[ "$HOST" == *"admin"* ]]; then
      GROUP="internal"
  fi

  # Default protocol and path
  PROTO=${PROTO:-https}
  PATH_VAL=${PATH_VAL:-/}
  if [[ "$PATH_VAL" != /* ]]; then
    PATH_VAL="/$PATH_VAL"
  fi

  # Add endpoint configuration
  if [[ "$PROTO" == "tcp" ]]; then
    TCP_HOST=$(echo "$HOST" | sed 's/\/$//')
    cat >> "$OUTPUT_FILE" <<EOF
  - name: ${ENDPOINT_NAME}
    group: ${GROUP}
    url: "tcp://${TCP_HOST}"
    interval: ${CHECK_INTERVAL}
    conditions:
      - "[CONNECTED] == true"

EOF
  else
    cat >> "$OUTPUT_FILE" <<EOF
  - name: ${ENDPOINT_NAME}
    group: ${GROUP}
    url: "${PROTO}://${HOST}${PATH_VAL}"
    interval: ${CHECK_INTERVAL}
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > ${CERTIFICATE_EXPIRATION_THRESHOLD}"

EOF
  fi

  ((CONFIGURED_COUNT++))
done <<< "$UNIQUE_ENDPOINTS"

echo "Generated configuration file: $OUTPUT_FILE"
echo "Total endpoints configured: $CONFIGURED_COUNT"

# Validate the generated YAML (optional, requires yq)
if command -v yq &> /dev/null; then
  echo "Validating YAML syntax..."
  yq eval '.' "$OUTPUT_FILE" > /dev/null && echo "YAML is valid"
fi

echo "Configuration generation complete!"
